/* stored procedure for ediseases.com */
DELIMITER $$
SET @a = 0;
CREATE PROCEDURE rkb_update_menu_item_order(IN termslug VARCHAR(150))
BEGIN

SET @a = @a + 1;

SELECT `term_id` INTO @tid FROM `wpyo_terms` WHERE `slug`=termslug;
SELECT count(*) FROM `wpyo_terms` t INNER JOIN `wpyo_term_taxonomy` tt ON t.term_id=tt.term_id WHERE tt.parent=@tid; 

/*
UPDATE `wpyo_term_taxonomy` tt INNER JOIN `wpyo_terms` t ON t.term_id=tt.term_id SET tt.parent=@tid WHERE 
t.slug = CONCAT('types-',termslug) AND tt.parent=0 AND tt.taxonomy = 'category';
UPDATE `wpyo_term_taxonomy` tt INNER JOIN `wpyo_terms` t ON t.term_id=tt.term_id SET tt.parent=@tid WHERE 
t.`slug` = CONCAT('causes-',termslug) AND tt.parent=0 AND tt.taxonomy = 'category';
UPDATE `wpyo_term_taxonomy` tt INNER JOIN `wpyo_terms` t ON t.term_id=tt.term_id SET tt.parent=@tid WHERE 
t.`slug` = CONCAT('symptoms-',termslug) AND tt.parent=0 AND tt.taxonomy = 'category';
UPDATE `wpyo_term_taxonomy` tt INNER JOIN `wpyo_terms` t ON t.term_id=tt.term_id SET tt.parent=@tid WHERE 
t.`slug` = CONCAT('risk-factors-',termslug) AND tt.parent=0 AND tt.taxonomy = 'category';
UPDATE `wpyo_term_taxonomy` tt INNER JOIN `wpyo_terms` t ON t.term_id=tt.term_id SET tt.parent=@tid WHERE 
t.`slug` = CONCAT('treatment-',termslug) AND tt.parent=0 AND tt.taxonomy = 'category';
UPDATE `wpyo_term_taxonomy` tt INNER JOIN `wpyo_terms` t ON t.term_id=tt.term_id SET tt.parent=@tid WHERE 
t.`slug` = CONCAT('medication-',termslug) AND tt.parent=0 AND tt.taxonomy = 'category';
UPDATE `wpyo_term_taxonomy` tt INNER JOIN `wpyo_terms` t ON t.term_id=tt.term_id SET tt.parent=@tid WHERE 
t.`slug` = CONCAT('prevention-',termslug) AND tt.parent=0 AND tt.taxonomy = 'category';
*/
END$$
DELIMITER ;;

CALL rkb_update_menu_item_order('abscess');
CALL rkb_update_menu_item_order('acid-reflux');
CALL rkb_update_menu_item_order('acne');
CALL rkb_update_menu_item_order('aids');
CALL rkb_update_menu_item_order('alcoholism');
CALL rkb_update_menu_item_order('aneurysm');
CALL rkb_update_menu_item_order('anorexia');
CALL rkb_update_menu_item_order('anxiety');
CALL rkb_update_menu_item_order('appendicitis');
CALL rkb_update_menu_item_order('appendix');
CALL rkb_update_menu_item_order('arthritis');
CALL rkb_update_menu_item_order('aspergers');
CALL rkb_update_menu_item_order('asthma');
CALL rkb_update_menu_item_order('autism');
CALL rkb_update_menu_item_order('back-pain');
CALL rkb_update_menu_item_order('bad-breath');
CALL rkb_update_menu_item_order('bed-bugs');
CALL rkb_update_menu_item_order('bipolar');
CALL rkb_update_menu_item_order('bipolar-disorder');
CALL rkb_update_menu_item_order('blood-in-stool');
CALL rkb_update_menu_item_order('blood-pressure');
CALL rkb_update_menu_item_order('borderline-personality-disorder');
CALL rkb_update_menu_item_order('breast-cancer');
CALL rkb_update_menu_item_order('breast-lump');
CALL rkb_update_menu_item_order('broken-leg');
CALL rkb_update_menu_item_order('bronchitis');
CALL rkb_update_menu_item_order('bulimia');
CALL rkb_update_menu_item_order('burn');
CALL rkb_update_menu_item_order('burnout');
CALL rkb_update_menu_item_order('cad');
CALL rkb_update_menu_item_order('cancer');
CALL rkb_update_menu_item_order('candida');
CALL rkb_update_menu_item_order('canker-sore');
CALL rkb_update_menu_item_order('cardiac-arrest');
CALL rkb_update_menu_item_order('carpal-tunnel');
CALL rkb_update_menu_item_order('celiac-disease');
CALL rkb_update_menu_item_order('cellulitis');
CALL rkb_update_menu_item_order('cerebral-palsy');
CALL rkb_update_menu_item_order('cervical-cancer');
CALL rkb_update_menu_item_order('chicken-pox');
CALL rkb_update_menu_item_order('chlamydia');
CALL rkb_update_menu_item_order('cholesterol');
CALL rkb_update_menu_item_order('cold');
CALL rkb_update_menu_item_order('cold-sore');
CALL rkb_update_menu_item_order('cold-sores');
CALL rkb_update_menu_item_order('colitis');
CALL rkb_update_menu_item_order('colon-cancer');
CALL rkb_update_menu_item_order('concussion');
CALL rkb_update_menu_item_order('conjunctivitis');
CALL rkb_update_menu_item_order('constipation');
CALL rkb_update_menu_item_order('copd');
CALL rkb_update_menu_item_order('cyst');
CALL rkb_update_menu_item_order('cystic-fibrosis');
CALL rkb_update_menu_item_order('dementia');
CALL rkb_update_menu_item_order('depression');
CALL rkb_update_menu_item_order('diabetes-symptoms');
CALL rkb_update_menu_item_order('diarrhea');
CALL rkb_update_menu_item_order('dic');
CALL rkb_update_menu_item_order('diverticulitis');
CALL rkb_update_menu_item_order('down-syndrome');
CALL rkb_update_menu_item_order('dyslexia');
CALL rkb_update_menu_item_order('dystonia');
CALL rkb_update_menu_item_order('e-coli');
CALL rkb_update_menu_item_order('eating-disorders');
CALL rkb_update_menu_item_order('eczema');
CALL rkb_update_menu_item_order('emphysema');
CALL rkb_update_menu_item_order('endometriosis');
CALL rkb_update_menu_item_order('enema');
CALL rkb_update_menu_item_order('epilepsy');
CALL rkb_update_menu_item_order('erectile-dysfunction');
CALL rkb_update_menu_item_order('falling');
CALL rkb_update_menu_item_order('fever');
CALL rkb_update_menu_item_order('fibromyalgia-symptoms');
CALL rkb_update_menu_item_order('flu');
CALL rkb_update_menu_item_order('food-poisoning');
CALL rkb_update_menu_item_order('frostbite');
CALL rkb_update_menu_item_order('gallstones');
CALL rkb_update_menu_item_order('genital-herpes');
CALL rkb_update_menu_item_order('genital-warts');
CALL rkb_update_menu_item_order('glaucoma');
CALL rkb_update_menu_item_order('gonorrhea');
CALL rkb_update_menu_item_order('gout');
CALL rkb_update_menu_item_order('guillain-barre-syndrome');
CALL rkb_update_menu_item_order('hair-loss');
CALL rkb_update_menu_item_order('head-lice-infestation');
CALL rkb_update_menu_item_order('headache');
CALL rkb_update_menu_item_order('hearing-loss');
CALL rkb_update_menu_item_order('heart-attack');
CALL rkb_update_menu_item_order('heart-diseases');
CALL rkb_update_menu_item_order('hemophilia');
CALL rkb_update_menu_item_order('hemorrhoids');
CALL rkb_update_menu_item_order('hepatitis');
CALL rkb_update_menu_item_order('hepatitis-b');
CALL rkb_update_menu_item_order('hepatitis-c');
CALL rkb_update_menu_item_order('hernia');
CALL rkb_update_menu_item_order('herpes-symptoms');
CALL rkb_update_menu_item_order('hiccups');
CALL rkb_update_menu_item_order('high-blood-pressure');
CALL rkb_update_menu_item_order('hiv');
CALL rkb_update_menu_item_order('hiv-symptoms');
CALL rkb_update_menu_item_order('hives');
CALL rkb_update_menu_item_order('hpv');
CALL rkb_update_menu_item_order('hsv');
CALL rkb_update_menu_item_order('hypertension');
CALL rkb_update_menu_item_order('hyperthyroidism');
CALL rkb_update_menu_item_order('hypothyroidism');
CALL rkb_update_menu_item_order('ibs');
CALL rkb_update_menu_item_order('impetigo');
CALL rkb_update_menu_item_order('irritable-bowel-movement');
CALL rkb_update_menu_item_order('kidney-stones');
CALL rkb_update_menu_item_order('laryngitis');
CALL rkb_update_menu_item_order('leprosy');
CALL rkb_update_menu_item_order('leukaemia');
CALL rkb_update_menu_item_order('lice');
CALL rkb_update_menu_item_order('liver-disease');
CALL rkb_update_menu_item_order('low-back-pain');
CALL rkb_update_menu_item_order('lung-cancer');
CALL rkb_update_menu_item_order('lupus');
CALL rkb_update_menu_item_order('lyme-disease');
CALL rkb_update_menu_item_order('lymphoma');
CALL rkb_update_menu_item_order('measles');
CALL rkb_update_menu_item_order('melanocytic-nevus');
CALL rkb_update_menu_item_order('melanoma');
CALL rkb_update_menu_item_order('meningitis');
CALL rkb_update_menu_item_order('menopause');
CALL rkb_update_menu_item_order('mesothelioma');
CALL rkb_update_menu_item_order('migraine');
CALL rkb_update_menu_item_order('mono');
CALL rkb_update_menu_item_order('mononucleosis');
CALL rkb_update_menu_item_order('mrsa');
CALL rkb_update_menu_item_order('multiple-sclerosis');
CALL rkb_update_menu_item_order('muscular-dystrophy');
CALL rkb_update_menu_item_order('narcissistic-personality-disorder');
CALL rkb_update_menu_item_order('nausea');
CALL rkb_update_menu_item_order('obesity');
CALL rkb_update_menu_item_order('ocd');
CALL rkb_update_menu_item_order('odd');
CALL rkb_update_menu_item_order('osteoarthritis');
CALL rkb_update_menu_item_order('osteoporosis');
CALL rkb_update_menu_item_order('pad');
CALL rkb_update_menu_item_order('pancreatic-cancer');
CALL rkb_update_menu_item_order('pancreatitis');
CALL rkb_update_menu_item_order('panic-attacks');
CALL rkb_update_menu_item_order('pcos');
CALL rkb_update_menu_item_order('piles');
CALL rkb_update_menu_item_order('pink-eye');
CALL rkb_update_menu_item_order('plantar-fasciitis');
CALL rkb_update_menu_item_order('pneumonia');
CALL rkb_update_menu_item_order('pneumonia-symptoms');
CALL rkb_update_menu_item_order('poison-ivy');
CALL rkb_update_menu_item_order('polio');
CALL rkb_update_menu_item_order('post-traumatic-stress-disorder');
CALL rkb_update_menu_item_order('progeria');
CALL rkb_update_menu_item_order('prostate-cancer');
CALL rkb_update_menu_item_order('psoriasis');
CALL rkb_update_menu_item_order('ptsd');
CALL rkb_update_menu_item_order('rabies');
CALL rkb_update_menu_item_order('rash');
CALL rkb_update_menu_item_order('rds');
CALL rkb_update_menu_item_order('rheumatoid-arthritis');
CALL rkb_update_menu_item_order('ringworm');
CALL rkb_update_menu_item_order('rosacea');
CALL rkb_update_menu_item_order('salmonella');
CALL rkb_update_menu_item_order('sars');
CALL rkb_update_menu_item_order('scabies');
CALL rkb_update_menu_item_order('scarlet-fever');
CALL rkb_update_menu_item_order('schizophrenia');
CALL rkb_update_menu_item_order('sciatica');
CALL rkb_update_menu_item_order('scoliosis');
CALL rkb_update_menu_item_order('shingles');
CALL rkb_update_menu_item_order('skin-cancer');
CALL rkb_update_menu_item_order('sleep-apnea');
CALL rkb_update_menu_item_order('sneeze');
CALL rkb_update_menu_item_order('sore-throat');
CALL rkb_update_menu_item_order('std');
CALL rkb_update_menu_item_order('strep-throat');
CALL rkb_update_menu_item_order('stress');
CALL rkb_update_menu_item_order('stroke');
CALL rkb_update_menu_item_order('supraventricular-tachycardia');
CALL rkb_update_menu_item_order('symptoms-of-swine-flu');
CALL rkb_update_menu_item_order('syphilis');
CALL rkb_update_menu_item_order('thrush');
CALL rkb_update_menu_item_order('tia');
CALL rkb_update_menu_item_order('tick');
CALL rkb_update_menu_item_order('tinnitus');
CALL rkb_update_menu_item_order('tired');
CALL rkb_update_menu_item_order('tonsillitis');
CALL rkb_update_menu_item_order('tuberculosis');
CALL rkb_update_menu_item_order('urinary-tract-infection');
CALL rkb_update_menu_item_order('vertigo');
CALL rkb_update_menu_item_order('vitiligo');
CALL rkb_update_menu_item_order('yeast-infection');

DROP PROCEDURE IF EXISTS rkb_update_menu_item_order;